<?php

/**
 * @file
 * Module file for the WalkMe Snippet module.
 */

use Drupal\Core\Render\Markup;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function walkme_snippet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the walkme_snippet module.
    case 'help.page.walkme_snippet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides ability to integrate Drupak with Walkme.') . '</p>';
      return $output;

    default:
  }

}

/**
 * Implements hook_page_attachments().
 */
function walkme_snippet_page_attachments(array &$page) {
  // Check the snippet visibity on admin pages.
  if (\Drupal::config('walkme_snippet.settings')->get('walkme_admin') && \Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $walkmeScript = \Drupal::config('walkme_snippet.settings')->get('walkme_script');
  if ($walkmeScript) {
    $page['#attached']['html_head'][] = [
      [
        '#tag' => 'script',
        '#value' => Markup::create($walkmeScript),
      ],
      'walkme_snippet',
    ];
  }

}
